name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Cambia esto a la rama que uses

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Paso 3: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t howl0y/howleb:latest .

      # Paso 4: Subir la imagen a Docker Hub
      - name: Push Docker image
        run: |
          docker push howl0y/howleb:latest

      # Paso 5: Configurar kubectl para acceder al cluster de Kubernetes
      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Paso 6: Autenticación en el cluster de Kubernetes
      - name: Authenticate to Kubernetes cluster
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      # Paso 7: Actualizar el despliegue en Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/nextjs-app nextjs-app=howl0y/howleb:latest