name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Activa el workflow cuando se hace push a la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Paso 3: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t howl0y/howleb:latest .

      # Paso 4: Subir la imagen a Docker Hub
      - name: Push Docker image
        run: |
          docker push howl0y/howleb:latest